options:
  substitution_option: ALLOW_LOOSE

substitutions:
  _SERVICE_NAME: "signal-remains"
  _REGION: "us-central1"

steps:
  # 1. Fetch GEMINI_API_KEY from Secret Manager
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: fetch-secrets
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "ðŸ” Fetching Gemini API key from Secret Manager..."
        GEMINI_API_KEY=$(gcloud secrets versions access latest --secret=gemini-api-key)
        echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> /workspace/secrets.env

  # 2. Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '.'
    ]

  # 3. Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push-image
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  # 4. Deploy to Cloud Run with GEMINI_API_KEY injected at runtime
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-cloudrun
    entrypoint: bash
    args:
      - '-c'
      - |
        source /workspace/secrets.env
        echo "ðŸš€ Deploying to Cloud Run..."
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "GEMINI_API_KEY=$GEMINI_API_KEY"

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
